name: demo4444
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio:
  get_storage:
  http:
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_native_splash:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: "assets/flutter_logo.png"
  android: true
  web: true

flutter: 
  uses-material-design: true
  assets:
    - assets/

